name: Continuous integration

on:
  push:
    branches: ['**']

jobs:
  lint-test-and-publish:
    name: Unit test and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: sbt

      - run: sbt 'scalafixAll --check' scalafmtSbtCheck scalafmtCheck

      - run: sbt +test

      - run: sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}
